version: '3'

services:
  bind9:
    container_name: dns
    image: ubuntu/bind9:latest
    environment:
    - BIND9_USER=root
    ports:
    - "53:53/tcp"
    - "53:53/udp"
    volumes:
    - ./bind:/etc/bind
    restart: unless-stopped

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./html/hosting-laplata.com.ar:/usr/share/nginx/hosting-laplata.com.ar
      - ./html/hosting-laplata.xyz:/usr/share/nginx/hosting-laplata.xyz
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
      - node

  php:
    image: php:8.0-fpm
    volumes:
      - ./html/hosting-laplata.com.ar:/usr/share/nginx/hosting-laplata.com.ar
      - ./html/hosting-laplata.xyz:/usr/share/nginx/hosting-laplata.xyz
    restart: unless-stopped

  node:
    image: node:latest
    volumes:
      - ./nodejs/:/usr/src/app
    working_dir: /usr/src/app
    command: sh -c "npm install && npm run build && npm start"
    ports:
      - "3000:3000"
    restart: unless-stopped

